row/col/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.table),
]

row/row/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('col.urls')),
]

row/col/models.py
from django.db import models

# Create your models here.


STATE_CHOICE = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Thiruvananthapuram', 'Thiruvananthapuram'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttarakhand', 'Uttarakhand'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('West Bengal', 'West Bengal'),
)


class Resume(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    gender = models.CharField(max_length=100)
    locality = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    pin_code = models.PositiveIntegerField()
    state = models.CharField(choices=STATE_CHOICE, max_length=50)
    mobile = models.PositiveIntegerField()
    email = models.EmailField()
    courses = models.CharField(max_length=50)

row/col/forms.py
from django import forms
from .models import Resume


class DateInput(forms.DateInput):
    input_type = 'date'


GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]

COURSES_CHOICE = [
    ('Python', 'Python'),
    ('Java', 'Java'),
    ('DotNet', 'DotNet'),
    ('C and Cpp', 'C and Cpp'),
    ('Php', 'Php')
]


class ResumeForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)
    courses = forms.MultipleChoiceField(label='Selective Courses', choices=COURSES_CHOICE,
                                        widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Resume
        fields = '__all__'

        labels = {
            'name': 'Full Name',
            'dob': 'Date of Birth',
            'gender': 'Gender',
            'locality': 'Locality',
            'city': 'City',
            'pin_code': 'Pin code',
            'state': 'State',
            'mobile': 'Phone Number',
            'email': 'Email ID',
            'courses': 'Selective Courses'
        }

        widgets = {


            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': DateInput(attrs={'class': 'form-control'}),
            'gender': forms.TextInput(attrs={'class': 'form-control'}),
            'locality': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'pin_code': forms.NumberInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'mobile': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'courses': forms.TextInput(attrs={'class': 'form-control'})

        }

row/col/views.py
from django.shortcuts import render
from .forms import ResumeForm
from .models import Resume


# Create your views here.

def table(request):
    if request.method == "POST":
        form = ResumeForm(request.POST)
        if form.is_valid():
            form.save()
    form = ResumeForm()
    dict_form = {
        'form': form
    }
    return render(request, 'db.html', dict_form)

row/templates/db.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <style>
      #id_gender{
      display: inline-flex;
      padding-left: 20px;
      }
      #id_gender > div{
      padding-left:20px;
      }
      #id_courses{
      display: inline-flex;
      padding-left: 20px;
      }
      #id_courses > div{
      padding-left:20px;
      }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
    $( function() {
    $( "#datepicker" ).datepicker();
    } );
  </script>
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
  <div class="container">
    <div class="alert alert-success text-center"><b>Fill the Form</b></div>
    <div class="row">
      <div class="col-sm-8 alert alert-primary">
        <form action="" method="POST" class="shadow p-5">
          {% csrf_token %}
          {{form.as_p}}
          <!--<input type="submit" value="Submit" class="btn btn-danger mx-6">-->
          <div class="text-center">
            <button type="submit" class="btn btn-primary mt-3 px-4">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
  </body>
</html>